### ISSUE TITLE
Modify PR template to include issue resolution

### ISSUE THREAD

**Issue by jonschwartz** [jonschwartz/steffi#7]
### modify PR template to include issue resolution

Modify PULL_REQUEST_TEMPLATE.md to include language about which issue a particular PR is fixing

**Comment by omeiirr** [comment]
I'd like to work on this issue.

**Comment by jonschwartz** [comment]
@omeiirr Awesome!  I am just getting started on this project so I'm happy for the help.  Assigning to you.

**Comment by omeiirr** [comment]
@jonschwartz 
Just a quick question. 
What do we mean by "language about which issue a particular PR"?

**Comment by jonschwartz** [comment]
Sorry I wasn't super specific on this but I think what it should say is something like 
"Resolves Issue #{issue number}" So when someone is filling in their PR message, they can easily tie the PR back to an existing issue.

**Comment by omeiirr** [comment]
@jonschwartz 
Created a PR [here](https://github.com/jonschwartz/steffi/pull/15)
Please review 😄

**Comment by jonschwartz** [comment]
@omeiirr Merged.  Thanks for helping!

**Comment by omeiirr** [comment]
Thanks for my first PR ever! ⭐

**Comment by jonschwartz** [comment]
You're very welcome!  This is my first open source project ever!  I'm very happy to have someone willing to contribute already and even more so that you're new to contributing!
